#
# IMPORTANTE
#
# Codcov no est√° configurador
# No utilizar, es experimental

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target

